version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=landry
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=vocab_db
    ports:
      - "5432:5432"  # Accessible depuis ton script Python local sur le port 5432

volumes:
  postgres_data: